### PR TITLE
Add root_module and wrap_in_module options

### PR DESCRIPTION
**Pull request by chih-hung**
* When root_module=true do not emit code that fails to compile
  as a root module.
* When wrap_in_module=name is given, add a wrapper around output:
        pub mod name { ... }
  This allows the output file to be "included" and compiled.

### CODE REVIEW

**Comment by chih-hung** [comment]
The root_module option could be used to solve issue https://github.com/stepancheg/rust-protobuf/issues/493
The wrap_in_module option was the proposed workaround for issue https://github.com/stepancheg/rust-protobuf/issues/117

**Comment by stepancheg** [comment]
hi Chin-Hung, can you provide a more detailed example of how to is supposed to work?

Generally, I'm currently working on version 3 release, and it would be great if we could finally solve this issue, make some solution which should work fine by default.

**Comment by chih-hung** [comment]
I imported protobuf-codegen to the Android platform and used it as a plugin with Android's port of protoc. Android build system does not call cargo to build. It calls protoc to compile protobuf files into Rust files and calls rustc to compile the generated files.
One of my case uses the include! macro to include the generated file into into another file to compile. This has compilation error of issue #117, and needs to use the option wrap_in_module=some_module.
Another case generates a rust file and compile the file as a root module into a library to link with other rust code. This has compilation error of issue #493, and needs the option root_module=true.

**Comment by clintfred** [comment]
Not sure if this is related. I am still using the workaround I stated [here](https://github.com/stepancheg/rust-protobuf/issues/117#issuecomment-548590840) to wrap my generated code in modules. When upgrading to 2.17 that solution broke because of the addition of 
```
#![rustfmt::skip]
```

which according to https://github.com/rust-lang/rust/issues/5472 is only allowed at the top level. My interim solution is to remove the skip directive from the generated code. 

Maybe there's a better way of generating code inside of modules now, or maybe that's what this PR is about?

**Comment by stepancheg** [comment]
To handle generated code we agreed to proceed with https://github.com/stepancheg/rust-protobuf/pull/525. @clintfred have a look and tell what you think (if you have something to say) before this option is ported to the stable branch and released.

**Comment by chih-hung** [comment]
Yes, I agree that #525 can replace this PR.
