### ISSUE TITLE
#![rustfmt::skip]: non-builtin inner attributes are unstable

### ISSUE THREAD

**Issue by WalterSmuts** [stepancheg/rust-protobuf#534]
I'm a bit new to rust so please bear with me here :) I'm trying to use the protobuf library but can only get it to compile when I add the `+nightly` flag to `cargo`:
```
wssmts@laptop:~/Programs/rust-ipc/rust-protobuf > cargo +nightly build
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
```
Everything works fine using the nightly compiler, but I am a bit hesitant using this in a production system with the nightly compiler building using actual unstable features.

So I looked around in the [documentation](https://crates.io/crates/protobuf), the [github readme](https://github.com/stepancheg/rust-protobuf/blob/master/README.md) and the [the issues mentioning nightly](https://github.com/danburkert/prost/issues?q=nightly) and couldn't find anything refering to having to use the nightly compiler to use the `protobuf` crate.

So I guess the question is, do I have to use the nightly compiler if I need this library?

If not, and I almost assume not, what am I doing wrong?

#### My setup
[My repo](https://github.com/WalterSmuts/rust-ipc/tree/master/rust-protobuf)
Versions etc
```
wssmts@laptop:~/Programs/rust-ipc/rust-protobuf > cargo -V
cargo 1.41.0 (626f0f40e 2019-12-03)
wssmts@laptop:~/Programs/rust-ipc/rust-protobuf > rustc -V
rustc 1.41.0 (5e1a79984 2020-01-27)
wssmts@laptop:~/Programs/rust-ipc/rust-protobuf > rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/ANT.AMAZON.COM/wssmts/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.38.0-x86_64-unknown-linux-gnu
1.41.0-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

aarch64-unknown-linux-musl
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl

active toolchain
----------------

1.41.0-x86_64-unknown-linux-gnu (default)
rustc 1.41.0 (5e1a79984 2020-01-27)


```
Error output without compiling using nightly
```
wssmts@laptop:~/Programs/rust-ipc/rust-protobuf > cargo build
   Compiling protobuf v2.18.1
error[E0658]: non-builtin inner attributes are unstable
 --> /home/ANT.AMAZON.COM/wssmts/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.18.1/src/descriptor.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726

<SNIP> Basically repeats the same error </SNIP>
```

**Comment by stepancheg** [comment]
Can you please check with the latest rust? Version 1.41.0 you are using is 10 months old.

Alternatively, try using some older version of rust-protobuf.

I don't know what's the official minimum supported rust version of rust-protobuf because I accidentally broke CI testing with older versions.

**Comment by stepancheg** [comment]
Just checked, latest stable version works with rust versions starting with 1.44.1.

**Comment by stepancheg** [comment]
OK, it's actually even [mentioned in changelog](https://github.com/stepancheg/rust-protobuf/blob/master/CHANGELOG.md#2150---2020-06-21).

Closing the issue now, please reopen or create another one if the issue still exists or something other help is needed.
