### PR TITLE
Use `allow(clippy::all)` instead of `allow(clippy)` as reccomended.

### LINKED ISSUE #331: `#[allow(clippy)]` should be `#[allow(clippy::all)]` now.
Clippy itself now recommends using this instead:

```
warning: lint name `clippy` is deprecated and may not have an effect in the future. Also `cfg_attr(cargo-clippy)` won't be necessary anymore
 --> src/eraftpb.rs:6:10
  |
6 | #![allow(clippy)]
  |          ^^^^^^ help: change it to: `clippy::all`
  |
  = note: #[warn(renamed_and_removed_lints)] on by default
```

### PR DESCRIPTION
**Pull request by Hoverbear**
Closes #331 .

Note this currently requires a nightly only feature. Users would have to be using something like:

```rust
#![cfg_attr(feature = "cargo-clippy", feature(tool_lints))]
```

### CODE REVIEW

**Comment by stepancheg** [comment]
CI builds fail.

**Comment by Hoverbear** [comment]
@stepancheg Should be good to go.

**Comment by peterhuene** [comment]
I'm running into this issue on my lints (I like to treat linter warnings as errors in CI).

Any chance that this could be merged for a new release?

**Comment by stepancheg** [comment]
Well, the problem with this version of patch is that it assumes that feature is named `cargo-clippy`.

So in order to use clippy in generated code, client project must explicitly declare that feature which name is hardcoded.

I have a couple of ideas how to solve it:
* patch codegen to generate code without clippy warnings in generated code (so clippy mute won't be necessary). Don't know how hard would it be.
* provide codegen option to generate clippy annotation (same way there's a [codegen option to generate serde annotations](https://github.com/stepancheg/rust-protobuf/blob/447d99e9b6398686f808499028776ee1237e41b1/protobuf-codegen/src/customize.rs#L31))
* generate clippy annotations in user post-processors: https://github.com/stepancheg/rust-protobuf/issues/338
* generate `#[cfg_attr(protobuf-clippy, ...)]` instead of #[cfg_attr(feature = "cargo-clippy", ...)]`

**Comment by Hoverbear** [comment]
@stepancheg Clippy explicitly adds this feature when run: https://github.com/rust-lang-nursery/rust-clippy#allowingdenying-lints

**Comment by stepancheg** [comment]
@Hoverbear thank you for the explanations! I will merge the PR soon.

**Comment by stepancheg** [comment]
Pushed to master as 493de4dc1c67e3fb59407ce842d836b0a6ca0214.

**Comment by stepancheg** [comment]
Merged to 2.1 branch...

**Comment by stepancheg** [comment]
I don't know what to do, because I don't use clippy myself.

Should I revert that diff?

**Comment by Hoverbear** [comment]
Oh no, I'm sorry. We use nightly so I didn't think of it.

Right now using `#![cfg_attr(feature = "cargo-clippy", allow(clippy::all))]` is nightly only, but stable works with `#![cfg_attr(feature = "cargo-clippy", allow(clippy))]`. However that throws a warning on nightly. :sob:

**Comment by knkski** [comment]
Would it work to do something like this?

```
#![cfg_attr(feature = "cargo-clippy,stable", allow(clippy))]
#![cfg_attr(feature = "cargo-clippy,nightly", allow(clippy::all))]
```

It might be worth running clippy in travisci, even if you ignore the lint warnings that it gives, since compilation errors like this would still get alerted

**Comment by stepancheg** [comment]
I'll revert that diff for now, and let's decide how to do this thing properly.

**Comment by chefsalim** [comment]
Just FYI, I got around this by adding the following to the mod declaration:
#[(allow(renamed_and_removed_lints)]

Clippy then did not generate any warnings for the protobuf code.

**Comment by azban** [comment]
any ideas on how to get this into master?

**Comment by Ten0** [comment]
Running on latest stable, simply replacing `#![allow(clippy)]` by `#![allow(clippy::all)]` works.
I'm still hitting warnings due to this, it's annoying.
Is there still anything that prevents us from fixing this ?

**Comment by stepancheg** [comment]
Will that `#![allow(clippy::all)]` work in Rust 1.27 which is current minimum supported Rust version for rust protobuf?

**Comment by Ten0** [comment]
> Will that `#![allow(clippy::all)]` work in Rust 1.27 which is current minimum supported Rust version for rust protobuf?

I guess I can open a PR and see if it passes travis ?

**Comment by stepancheg** [comment]
@Ten0 feel free to do that!

**Comment by stepancheg** [comment]
OK, I just checked

```
% git diff
diff --git a/protobuf/src/descriptor.rs b/protobuf/src/descriptor.rs
index fae68a27..aa8b0032 100644
--- a/protobuf/src/descriptor.rs
+++ b/protobuf/src/descriptor.rs
@@ -4,6 +4,7 @@
 // https://github.com/Manishearth/rust-clippy/issues/702
 #![allow(unknown_lints)]
 #![allow(clippy)]
+#![allow(clippy::all)]

 #![cfg_attr(rustfmt, rustfmt_skip)]

```

```
cargo +1.27.2 check
```

So I assume we just need to generate both `#![allow(clippy)]` and `#![allow(clippy::all)]`.

**Comment by stepancheg** [comment]
OK, I committed to v2.7 d01f19c078c54b4ce7ac57db7be58761b58cdf27 and master 12142588f5f4d165d2dd646aaa541e26651e4ef3.

CI passes (except ICE in master unrelated to this change).

Somebody who understands how to use clippy please confirm that this is proper and sufficient fix.

**Comment by stepancheg** [comment]
No it's not enough.

Now `cargo clippy` complains

```
warning: lint name `clippy` is deprecated and may not have an effect in the future. Also `cfg_attr(cargo-clippy)` won't be necessary anymore
 --> protobuf/src/well_known_types/api.rs:6:10
  |
6 | #![allow(clippy)]
  |          ^^^^^^ help: change it to: `clippy::all`

```

I don't know is it possible to mute this warning.

**Comment by stepancheg** [comment]
... which is completely unreasonable: `clippy::all` should obviously mute this message.

**Comment by stepancheg** [comment]
So I think we should just drop `#[allow(clippy)]`, Rust compiler is happy with `#[allow(clippy::all)]` and nobody should be using older than rust stable clippy.

**Comment by stepancheg** [comment]
7d8e7fa9b00acbc1e807e3227a55750d0349d6f6 is in v2.7 and d8d6ddac160292b87be1b2b6f6ee05795e3d42f8 in master.

**Comment by stepancheg** [comment]
Published 2.7.0.
