### ISSUE TITLE
version 2.27 uses recently stable feature

### ISSUE THREAD

**Issue by wpbrown** [stepancheg/rust-protobuf#600]
Trying to build with `rustc 1.54.0`:

```
error[E0658]: use of unstable library feature 'maybe_uninit_extra'
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.27.0/src/coded_output_stream.rs:211:62
    |
211 |         unsafe { (&mut *self.buffer)[self.position as usize].write(byte) };
    |                                                              ^^^^^
    |
    = note: see issue #63567 <[https://github.com/rust-lang/rust/issues/63567>](https://github.com/rust-lang/rust/issues/63567%3E) for more information
```

**Comment by stepancheg** [comment]
1.55 is September 2021. Let me check if I can make it work with earlier version.

**Comment by wpbrown** [comment]
we can lock the previous release as a workaround until we can upgrade the compiler. maybe just documenting the MSRV in the README is enough if the fix is too much work. thank you.

**Comment by stepancheg** [comment]
> maybe just documenting the MSRV in the README

I usually document it in changelog

https://github.com/stepancheg/rust-protobuf/blob/d1cb2b8875922843ba83a5228214c94a701f935c/CHANGELOG.md#L70-L73

**Comment by stepancheg** [comment]
Yes, it's doable, need to copy-paste two functions from rust stdlib. I'll do it later today.

**Comment by stepancheg** [comment]
I mean, port stable branch back to version 1.52.1.

**Comment by stepancheg** [comment]
Published rust-protobuf=2.27.1 compatible with rust>=1.52.1.
